openapi: 3.0.0
info:
  title: Contacts API
  description: API for managing contact information
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: List of contacts
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - phone
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '201':
          description: Contact created successfully

  /contacts/{id}:
    get:
      summary: Get contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact found
        '404':
          description: Contact not found

    put:
      summary: Update contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Contact updated
        '404':
          description: Contact not found

    delete:
      summary: Delete contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact deleted
        '404':
          description: Contact not found
